return {
  -- 'olimorris/codecompanion.nvim',
  -- dependencies = {
  --   'nvim-lua/plenary.nvim',
  --   'nvim-treesitter/nvim-treesitter',
  -- },
  -- opts = {
  --   adapters = {
  --     ollama = function()
  --       return require('codecompanion.adapters').extend('ollama', {
  --         env = {
  --           url = 'http://192.168.1.78:11434',
  --         },
  --         headers = {
  --           ['Content-Type'] = 'application/json',
  --         },
  --         parameters = {
  --           sync = true,
  --         },
  --         schema = {
  --           model = {
  --             default = 'deepseek-r1:14b',
  --           },
  --         },
  --       })
  --     end,
  --   },
  --   strategies = {
  --     chat = {
  --       adapter = 'ollama',
  --     },
  --     inline = {
  --       adapter = 'ollama',
  --     },
  --   },
  -- },
}
